Sprint 9 solution http api
AndrewVarvarich/java-kanban pull request #4
Opened 2024-06-09 09:01 UTC by AndrewVarvarich

2024-06-10 18:36 UTC, Fleaman777 requested changes

2024-06-10 18:36 UTC, Fleaman777 commented on src/webapi/BaseHttpHandler.java
> +    private void sendResponse(HttpExchange httpExchange, int statusCode, String response) throws IOException {
в этом методе можно было бы отловить IOException и правильно обработать, тогда мы не пришлось его пробрасывать в каждм методе, который испольщует этот sendResponse

2024-06-10 18:36 UTC, Fleaman777 commented on test/HttpTaskServerTest.java
> +    Gson gson = HttpTaskServer.getGson();
в тестах тоже хорошо придерживаться приницпа инкапсуляцтт, что бы было иденообрзие во всем коде

2024-06-10 18:36 UTC, Fleaman777 commented on test/HttpTaskServerTest.java
> +    public void testAddEpic() throws IOException, InterruptedException {
хорошо было бы в названии указать условие при котором выполняется тест и ожидаемый результат, что улучшило бы восприятие таких тестов

2024-06-10 18:36 UTC, Fleaman777 commented on test/HttpTaskServerTest.java
> +        Epic epic = new Epic("Epic 1", "Epic description", TaskStatus.NEW);
какие-то общие вещи можно было бы вынести в общие поля или в метод с аннотацией BeforeEach

2024-06-10 18:36 UTC, Fleaman777 commented on test/InMemoryTaskManagerTest.java
> +        taskManager.clearEpics();
так и напрашивается вынести эту логику во что-то общее

2024-06-10 18:36 UTC, Fleaman777 commented on src/webapi/HttpTaskServer.java
> +                    case "tasks":
"tasks" и др можно было бы вынести в константы

2024-06-10 18:36 UTC, Fleaman777 commented on src/webapi/HttpTaskServer.java
> +        private static Task parseToObject(String json) {
а нужно ли этот и следующий методы делать статическим?

2024-06-10 18:36 UTC, Fleaman777 commented on src/webapi/HttpTaskServer.java
> +    }
хорошее разделение на более мелкие методы, что позволяет лучше читать код

2024-06-10 20:52 UTC, AndrewVarvarich commented on src/webapi/HttpTaskServer.java
> +        private static Task parseToObject(String json) {
Мне кажется их лучше сделать не статическими, так как они используют состояние экземпляра и зависят от него, следовательно делать их статическими - было ошибочное решение

2024-06-11 18:26 UTC, Fleaman777 approved these changes

2024-07-16 16:32 UTC, merged